2018-11-14 04:24:18,521 ERROR 17448 nodejs.ClusterClientNoResponseError: client no response in 10797816ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\H5project\2018\katoto_eggList\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 17448
hostname: LAPTOP-236D5NH2

2018-11-14 19:57:34,592 ERROR 17448 nodejs.ClusterClientNoResponseError: client no response in 55974690ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\H5project\2018\katoto_eggList\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 17448
hostname: LAPTOP-236D5NH2

2018-11-14 21:23:29,587 ERROR 17448 nodejs.ClusterClientNoResponseError: client no response in 752692ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\H5project\2018\katoto_eggList\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 17448
hostname: LAPTOP-236D5NH2

